server:
  port: 40001

spring:
  application:
    name: auth-service
  profiles:
    active: @environment@
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

feign:
  sentinel:
    enabled: true

iot:
  jwt:
    secret: iot@Login(Auth}*^31)&iot%
    expire: 31622400
    sessionTimeout: 31536000