
server:
  port: 9999
#  configure for the sentinel-dashboard
spring:
  application:
    name: test-code
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: '08dcb5d1-d86d-4dda-be46-45bb795f2d3e'
        group: 'test-group'
  profiles:
    active: @environment@
feign:
  sentinel:
    enabled: true
#  circuitbreaker:
#    enabled=true: