server:
  port: 20001
spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.10.229:8080
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
feign:
  sentinel:
    enabled: true