server:
  port: 20001
spring:
  application:
    name: gateway-service
  profiles:
    active: @environment@
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test-code
          uri: lb://test-code
          filters:
            - StripPrefix=3
#            - name: Hystrix
#              args:
#                name: default
#                fallbackUri: forward:/fallback
          predicates:
            - Path=/api/v1/test-code/**
        - id: netty-service
          uri: lb://netty-service
          predicates:
            - Path=/websocket/**
        - id: socketio-service
          uri: lb://socketio-service
          predicates:
            - Path=/socket.io/**
gateway:
  ignoreUrl:
    - /websocket
feign:
  sentinel:
    enabled: true