server:
  port: 2021
spring:
  application:
    name: socketio-service
  profiles:
    active: @environment@
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

feign:
  sentinel:
    enabled: true